name: Echo message
on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: WriteMessage
        run: |
          echo "Hello, World!"
